### ISSUE TITLE
Unable to comsume cowin api from digital ocean machines hosted in BLR region.

### ISSUE THREAD

**Issue by omprakash7739** [cowinapi/developer.cowin#257]
Hi, Team
I have build an app which fetch data from this API :https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByDistrict?district_id=100&date=14-05-2021
for slot availability. I am using new machine hosted in BLR region but still i can't make any single API call ? 

My API call format looks some thing like this (NodeJs):- 

const makeRequest = (opt) => {
    return new Promise((resolve, reject) => {
        request(opt, (e, d) => {
            if (e) reject(e);
            else resolve(d);
        });
    });
};

const fetchData = (district_id, date) => {
let opt = {
            url: 'https://cdn-api.co-vin.in/api/v2/appointment/sessions/public/calendarByDistrict?' + 'district_id=' + district_id + '&' + 'date=' + date,
            method: 'GET',
            headers: {
                accept: 'application/json',
                'Accept-Language': 'hi_IN'
            }
        };
        let {body} = await makeRequest(opt);
        console.log(body);
        try {
            body = JSON.parse(body);
        
        } catch(e) {
           return  console.log(e);
        }

};

I am alway getting   error like this :- 

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>ERROR: The request could not be satisfied</TITLE>
</HEAD><BODY>
<H1>403 ERROR</H1>
<H2>The request could not be satisfied.</H2>
<HR noshade size="1px">
Request blocked.
We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
<BR clear="all">
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
<BR clear="all">
<HR noshade size="1px">
<PRE>
Generated by cloudfront (CloudFront)
Request ID: baKR-OUNuF2zIwHEKUyKyiZz8BrgYUITdCD8s8cWm7pLtoe8Z11iwA==
</PRE>
<ADDRESS>
</ADDRESS>
</BODY></HTML>
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at fetchAvailabilityDataForDistricts (/home/ubuntu/datafetcher/DataFetcher.js:1048:25)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by saran-surya** [comment]
Hello @omprakash7739, The API is geo fenced to INDIAN IP's only, if so you are using a NODE JS app, you can try this workaround, 
<b>
[https://github.com/saran-surya/cassata](https://github.com/saran-surya/cassata), I have this currently working in my SERVER hosted on Heroku in US region.

**Comment by akshch** [comment]
Hi @saran-surya, I am also facing the same problem and I am using the Ruby on Rails app, is there any workaround for this?

**Comment by saran-surya** [comment]
> Hi @saran-surya, I am also facing the same problem and I am using the Ruby on Rails app, is there any workaround for this?

I am currently working it around for PYTHON, will sure add this also into account, thanks for informing.
