### ISSUE TITLE
Cannot generate OTP from `axios` node.js

### ISSUE THREAD

**Issue by opticSquid** [cowinapi/developer.cowin#408]
# Please Help!
I'm having this code: 
```sh
var router = require("express").Router();
var axios = require("axios");
const OTPReciever = (req, res, next) => {
  var data = JSON.stringify({
    mobile: "PHONE_NUMBER",
  });

  var config = {
    method: "post",
    url: "https://cdn-api.co-vin.in/api/v2/auth/public/generateOTP",
    headers: {
      "Content-Type": "application/json",
    },
    data: data,
  };

  axios(config)
    .then(function (response) {
      console.log(JSON.stringify(response.data));
      res.status(200).json({ status: "ok" });
    })
    .catch(function (error) {
      console.log(error);
    });
};
router.get("/", OTPReciever);
module.exports = router;

```
I copied this code from `Postman` where the request was working properly. But as soon as I try to run this code from an Express server which is running on `localhost:5000` it results in error.
I will be providing the whole error here.
```sh
Error: Request failed with status code 403
    at createError (E:\IIC_Covid_Help\Server\node_modules\axios\lib\core\createError.js:16:15)
    at settle (E:\IIC_Covid_Help\Server\node_modules\axios\lib\core\settle.js:17:12)
    at IncomingMessage.handleStreamEnd (E:\IIC_Covid_Help\Server\node_modules\axios\lib\adapters\http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  config: {
    url: 'https://cdn-api.co-vin.in/api/v2/auth/public/generateOTP',
    method: 'post',
    data: '{"mobile":"PHONE_NUMBER"}',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/0.21.1',
      'Content-Length': 23
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus]
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      socket: [Function (anonymous)],
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      timeout: [Function (anonymous)],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: null,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'cdn-api.co-vin.in',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'cdn-api.co-vin.in',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 390,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _header: 'POST /api/v2/auth/public/generateOTP HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: application/json\r\n' +
      'User-Agent: axios/0.21.1\r\n' +
      'Content-Length: 23\r\n' +
      'Host: cdn-api.co-vin.in\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'fifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/api/v2/auth/public/generateOTP',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 403,
      statusMessage: 'Forbidden',
      client: [TLSSocket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'https://cdn-api.co-vin.in/api/v2/auth/public/generateOTP',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(RequestTimeout)]: undefined
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'cdn-api.co-vin.in',
    protocol: 'https:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 23,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'https://cdn-api.co-vin.in/api/v2/auth/public/generateOTP',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      'user-agent': [Array],
      'content-length': [Array],
      host: [Array]
    }
  },
  response: {
    status: 403,
    statusText: 'Forbidden',
    headers: {
      server: 'CloudFront',
      date: 'Mon, 07 Jun 2021 17:01:15 GMT',
      'content-type': 'text/html',
      'content-length': '919',
      connection: 'close',
      'x-cache': 'Error from cloudfront',
      via: '1.1 bcdc0fc6fb7aad2b2dbfca001ca794c9.cloudfront.net (CloudFront)',
      'x-amz-cf-pop': 'CCU50-C2',
      'x-amz-cf-id': '_KgCpWoMUmTTI1eR1Lw8O23kt7ymz9XkPagtezElYccqP0duFVKfrA=='
    },
    config: {
      url: 'https://cdn-api.co-vin.in/api/v2/auth/public/generateOTP',
      method: 'post',
      data: '{"mobile":"8617882389"}',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      validateStatus: [Function: validateStatus]
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'POST /api/v2/auth/public/generateOTP HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: axios/0.21.1\r\n' +
        'Content-Length: 23\r\n' +
        'Host: cdn-api.co-vin.in\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/v2/auth/public/generateOTP',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'cdn-api.co-vin.in',
      protocol: 'https:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">\n' +
      '<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">\n' +
      '<TITLE>ERROR: The request could not be satisfied</TITLE>\n' +
      '</HEAD><BODY>\n' +
      '<H1>403 ERROR</H1>\n' +
      '<H2>The request could not be satisfied.</H2>\n' +
      '<HR noshade size="1px">\n' +
      'Request blocked.\n' +
      "We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n" +
      '<BR clear="all">\n' +
      'If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.\n' +
      '<BR clear="all">\n' +
      '<HR noshade size="1px">\n' +
      '<PRE>\n' +
      'Generated by cloudfront (CloudFront)\n' +
      'Request ID: _KgCpWoMUmTTI1eR1Lw8O23kt7ymz9XkPagtezElYccqP0duFVKfrA==\n' +
      '</PRE>\n' +
      '<ADDRESS>\n' +
      '</ADDRESS>\n' +
      '</BODY></HTML>'
  },
  isAxiosError: true,
  toJSON: [Function: toJSON]
}
```

**Comment by parth-khiera** [comment]
You are not sending x-api-key mentioned in documentation.also add User-Agent using random-useragent in header.


headers: {
            'User-Agent': randomUseragent.getRandom(),
            'x-api-key' : '3sjOr2rmM52GzhpMHjDEE1kpQeRxwFDr4YcBEimi'
        }

**Comment by rahulshinde11** [comment]
I think doing this is not allowed. That OTP is for CoWin website.

**Comment by badinenisaivardhan** [comment]
Hey @soumalyatheking22012001 Here is the Working Code For Public And Protected API Generation Using Request In Nodejs. Hope This Help You

//Public API OTP GENERATION

var request = require('request');
var options = {
  'method': 'POST',
  'url': 'https://cdn-api.co-vin.in/api/v2/auth/public/generateOTP',
  'headers': {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0',
            'Accept': 'application/json, text/plain, */*',
            'Accept-Language': 'en-US,en;q=0.5',
            'Accept-Encoding': 'gzip, deflate, br',
            'Content-Type': 'application/json'
  },
  body: JSON.stringify({
    "mobile": "PhoneNumber"
  })

};
request(options, function (error, response) {
  if (error) throw new Error(error);
  console.log(response.body);
});



//Private Protected API OTP GENERATION
var mobilenumber = req.body.mobilenumber
        var options = {
        'method': 'POST',
        'url': 'https://cdn-api.co-vin.in/api/v2/auth/generateMobileOTP',
        'headers': {
            'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0',
            'Accept': 'application/json, text/plain, */*',
            'Accept-Language': 'en-US,en;q=0.5',
            'Accept-Encoding': 'gzip, deflate, br',
            'Content-Type': 'application/json'
        },
        body: JSON.stringify({
            "mobile": "PhoneNumber",
            "secret": "RandomSecretHash" //Can Be Obtained From Website XHR JSON-Body Call 
        })

        };
        request(options,mobilenumber, function (error, response) {
        if (error) throw new Error(error);
        console.log(response.body)
        });

**Comment by opticSquid** [comment]
> Hey @soumalyatheking22012001 Here is the Working Code For Public And Protected API Generation Using Request In Nodejs. Hope This Help You
> 
> //Public API OTP GENERATION
> 
> var request = require('request');
> var options = {
> 'method': 'POST',
> 'url': 'https://cdn-api.co-vin.in/api/v2/auth/public/generateOTP',
> 'headers': {
> 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0',
> 'Accept': 'application/json, text/plain, _/_',
> 'Accept-Language': 'en-US,en;q=0.5',
> 'Accept-Encoding': 'gzip, deflate, br',
> 'Content-Type': 'application/json'
> },
> body: JSON.stringify({
> "mobile": "PhoneNumber"
> })
> 
> };
> request(options, function (error, response) {
> if (error) throw new Error(error);
> console.log(response.body);
> });
> 
> //Private Protected API OTP GENERATION
> var mobilenumber = req.body.mobilenumber
> var options = {
> 'method': 'POST',
> 'url': 'https://cdn-api.co-vin.in/api/v2/auth/generateMobileOTP',
> 'headers': {
> 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0',
> 'Accept': 'application/json, text/plain, _/_',
> 'Accept-Language': 'en-US,en;q=0.5',
> 'Accept-Encoding': 'gzip, deflate, br',
> 'Content-Type': 'application/json'
> },
> body: JSON.stringify({
> "mobile": "PhoneNumber",
> "secret": "RandomSecretHash" //Can Be Obtained From Website XHR JSON-Body Call
> })
> 
> ```
>     };
>     request(options,mobilenumber, function (error, response) {
>     if (error) throw new Error(error);
>     console.log(response.body)
>     });
> ```

Thanks a lot it worked
